name: Mirror and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Get last merged PR title
        id: pr_title
        run: |
          gh auth setup-git
          gh pr list --state merged --base main --limit 1 --json title -q '.[0].title' > pr_title.txt
          echo "pr_title=$(cat pr_title.txt)" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: yunhayeon/plake
          token: ${{ secrets.GH_PAT }}
          path: target-repo

      - name: Copy files to target repo
        run: |
          rm -rf target-repo/*
          mkdir -p deploy
          ITEMS=(".next" "public" "src" "components.json" "next.config.mjs" \
                 "package.json" "package-lock.json" "postcss.config.mjs" \
                 "tailwind.config.ts" "tsconfig.json" \
                 "sentry.edge.config.ts" "sentry.server.config.ts" "sentry.client.config.ts")
          for ITEM in "${ITEMS[@]}"; do
            if [ -e "$ITEM" ]; then
              cp -r "$ITEM" deploy/
            else
              echo "⚠️ Warning: '$ITEM' not found, skipping..."
            fi
          done
          cp -r deploy/* target-repo/

      - name: Commit and push changes
        run: |
          cd target-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "${{ steps.pr_title.outputs.pr_title }}" || echo "⚠️ No changes to commit"
          git push origin main
